### ISSUE TITLE
Create Database Model

### ISSUE THREAD

**Issue by vkrishna1997** [CSCI-GA-2820-SU23-001/inventory#2]
**As a** developer
**I need** create a high level database model  
**So that** the team has a consistent high level understanding of what our resource's schema will look like
   
 ### Details and Assumptions
 The inventory service keeps track of how many of each product we have in our warehouse. 
 At a minimum it should reference:

-  product id
- quantity
- restock levels
- condition of the item (i.e., new, open box, used) as an enumeration.
- and their corresponding datatypes

*Restock levels will help you know when to order more products. 
*Being able to query products by their condition (e.g., new, used) could be very useful.
 
Document to be updated: https://dbdiagram.io/d/648a3907722eb77494fa8edc
Rev 1: https://dbdiagram.io/d/648dff3602bd1c4a5ea5d13f

 ### Acceptance Criteria  
   
 ```gherkin
 Given the database model is decided
 When we develop the inventory database
 Then we can reference the design document for tables, columns, relationships and datatypes
```

**Comment by IrregularHunterX** [comment]
Should this be labeled with technical debt instead of enhancement? As the user won't be aware of the DB model?

**Comment by vkrishna1997** [comment]
Agreed. I wasn't sure about that either but technical debt makes sense to me.

**Comment by IrregularHunterX** [comment]
I think the initial revision (https://dbdiagram.io/d/648a3907722eb77494fa8edc) looks good to me
