### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by vkrishna1997** [CSCI-GA-2820-SU23-001/inventory#31]
**As a** developer
**I need**  to document API endpoints
**So that** others using our API know the available endpoints
   
 ### Details and Assumptions
- Just a basic list of routes available.

For example:
### Inventory Operations
| Endpoint          | Methods | Rule
| ---------------   | ------- | --------------------------
| create_inventory  | POST    | ```/inventory```

**Comment by IrregularHunterX** [comment]
The readme file will be edited with all this new stuff, correct?
