### ISSUE TITLE
Implement CI

### ISSUE THREAD

**Issue by vkrishna1997** [CSCI-GA-2820-SU23-001/inventory#34]
**As a** developer
**I need** to implement CI
**So that** we can run unit tests to avoid breaking existing code
   
 ### Details and Assumptions

- Create a .github/workflows/tdd.yml file and configure GitHub
Actions to run your unit test cases every time someone pushes to
the master branch or submits a Pull Request.
- Do the same for the BDD test with a .github/workflows/bdd.yml file.
- Add a GitHub Actions CI badge to your README.md file so that
everyone will know if the build is broken.
- Maintain 95%+ code coverage
- Run our test cases to make sure that our tests work before
creating pull requests

 ### Acceptance Criteria  
   
 ```gherkin
 Given CI is functioning
 When a new PR is made
 Then CI will indicate if all existing unit tests passed
```

**Comment by IrregularHunterX** [comment]
Update
The automated unit tests pass, but need to figure out why linting and code coverage badges do not work (this will be addressed in the next sprint)
