### ISSUE TITLE
Create IBM Cloud accounts

### ISSUE THREAD

**Issue by vkrishna1997** [CSCI-GA-2820-SU23-001/inventory#35]
**As the** repo maintainer
**I need** everyone to make an IBM Cloud account  
**So that**  I can invite other members of our team to their IBM Cloud account and run Kubernetes Cluster successfully

   
 ### Details and Assumptions
**To make an account** follow instructions here: https://brightspace.nyu.edu/d2l/le/lessons/290206/topics/8714746 
**To invite users to dashboard** follow instructions here: https://brightspace.nyu.edu/d2l/le/lessons/290206/topics/8714747
  
 ### Acceptance Criteria  
   
 ```gherkin
 Given IBM cloud is working
 When everyone sets up their free accounts
 Then I can invite everyone to our dashboard
```

**Comment by IrregularHunterX** [comment]
We have all joined, is a PR needed for this item?

**Comment by vkrishna1997** [comment]
Nope. Going to close.

**Comment by IrregularHunterX** [comment]
iirc we only move items to "Closed" after the sprint retrospective?

**Comment by vkrishna1997** [comment]
Oh yeah that's right. I'm just used to hitting close issue after it's resolved. My b
