### ISSUE TITLE
Manual Deployment of Kubernetes Cluster

### ISSUE THREAD

**Issue by vkrishna1997** [CSCI-GA-2820-SU23-001/inventory#36]
**As a** developer
**I need** to manually deploy our application to a kubernetes cluster  on IBM cloud
**So that** our applications is persistent and publicly accessible
   
 ### Details and Assumptions
- Everyone on the team will need to make an IBM Cloud account.
Instructions will be provided before the Kubernetes labs.
- Create a Kubernetes cluster on IBM Cloud. You may use the same
one from our Kubernetes Lab.
- Add a /health endpoint to your service that returns
{"status":"OK}, 200 to be used as a health check for
Kubernetes.
- Create a dev namespace and a prod namespace in your
Kubernetes cluster to deploy the development and production
versions of our service. (Note: this is a Kubernetes namespace, not
a Container Registry namespace)
• IBM Cloud will not provide free accounts with a Kubernetes Ingress
so we will have to run your service as a NodePort. It is very
important that you use the following ports to avoid confusion when
grading: Development port is: 31001 and the Production port is:
31002
• Create the necessary Kubernetes metadata files for deployment
(deployment.yaml, service.yaml, secrets.yaml,
postgres.yaml, etc.) file so that Kubernetes will know how to
deploy our application.
• Use the Kubernetes CLI kubectl command to deploy our service
to our Kubernetes cluster manually.
• Get the IP address of our worker node and combine it with our port
to go to the URL of our service and make sure that it works

 ### Acceptance Criteria  
   
**Given** the kubernetes cluster is deployed and running,
**UPDATE**: Live worker pod external IP: 159.122.177.177:31000
When a call is made to the URL GET <IP_worker_pod>/health,
Then the API should return the status of the server in the following JSON format:
```gherkin
{
    <status> : "OK"
    <status_code> : 200
}
```

**Comment by IrregularHunterX** [comment]
Looks like it works
![image](https://github.com/CSCI-GA-2820-SU23-001/inventory/assets/113815338/71d60347-5bbe-4e6a-89e7-758a96cd183b)
